### ISSUE TITLE
Kebab case CSS class names not functioning in vite plugin

### ISSUE THREAD

**Issue by sultan99** [sultan99/stylin#5]
It fails to apply styles when the definition of CSS class names in kebab-case.

```scss
/**
  @tag: div
  @component: AvaBox
*/
.ava-box { // 👈 This class fails to work
  display: flex;

  > div + div {
    margin-left: 10px;
  }
}
```
